### ISSUE TITLE
test data or tutorial

### ISSUE THREAD

**Issue by nterhoeven** [holmrenser/IOGA#13]
Hi @holmrenser 

it would be nice to have some test data, so I can check, if my installation was successful. Also some more detailed instructions or a tutorial would be nice.

Best,

Niklas

**Comment by holmrenser** [comment]
Hi Niklas, 

Thanks for your interest in IOGA, your previous remarks and these questions make a lot of sense! Unfortunately, I don't have a lot of time to spare on updating IOGA at the moment. As you can probably tell from the repository, I have not really worked on the code for >5 years. I wrote the code as an MSc project, and have since moved on to a PhD position which I am finishing right now. 

I will try to add as much of your suggestions as possible, provided they don't take too much effort!

**Comment by holmrenser** [comment]
I am assuming you will not be submitting a pull request with your suggested changes, and I have updated the readme to reflect that I will not change anything to IOGA, since I do not have the time to actively maintain it.
